name = "ColPrac"
uuid = "e41b4c65-dcf0-4c1f-b7b6-bc66a3ea27a0"
version = "0.1.0"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com> and contributors"]

[compat]
ExplicitImports = "1.14.0"
julia = "1.6"

[extras]
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ExplicitImports", "Test"]
