name: Documentation

on:
  push:
    branches:
      - master
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      actions: write
      contents: write
      statuses: write
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    secrets: "inherit"
